<?php

/**
 * @file
 * Module file for bi_taxonomy_custom_controller.
 */

/**
 * Implements hook_theme().
 *
 * Defines the theming capabilities provided by this module.
 */
function bi_taxonomy_custom_controller_theme($existing, $type, $theme, $path) {
  return [
    'term_area'  => [
      // We use 'render element' when the item to be passed is a self-describing
      // render array (it will have #theme_wrappers)
      'render element' => 'element',
    ],
    'search_area'  => [
      'render element' => 'element',
    ],
  ];
}
