<?php

/**
 * @file
 * Module file for bi_taxonomy_custom_controller.
 */

/**
 * Implements hook_theme().
 *
 * Defines the theming capabilities provided by this module.
 */
function bi_taxonomy_custom_controller_theme($existing, $type, $theme, $path) {
  return [
    // 'term_area'  => [
    //   'variables' => [
    //     'title' => NULL,
    //     'description' => NULL,
    //   ],
    // ],
    'search_area'  => [
      // We use 'render element' when the item to be passed is a self-describing
      // render array (it will have #theme_wrappers)
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_page().
 */
function bi_taxonomy_custom_controller_preprocess_page(&$variables) {
  if ($term = \Drupal::routeMatch()->getParameter('taxonomy_term')) {
    $variables['term_description'] = $term->description->value;
  }
}

/**
 * Implements hook_preprocess_page_title().
 */
function bi_taxonomy_custom_controller_preprocess_page_title(&$variables) {
  if (\Drupal::routeMatch()->getRouteName() == 'entity.taxonomy_term.canonical') {
    $term= \Drupal::routeMatch()->getParameter('taxonomy_term');
    if ($term->bundle() == "tipi_di_notizia") {
      $variables['title']['#markup'] = $term->field_plurale->value;
    }
  }
}
